### ISSUE TITLE
Update resource prefixes and suffixes

### ISSUE THREAD

**Issue by ibersanoMS** [Azure/aks-baseline-windows#30]
Resources deployed seem to have a weird mix of suffix and prefix notation on resource name.  You’ll see both <item>-<resource-type-abbreviation> and also < resource-type-abbreviation >-<item> notation.  Please pick one and be consistent. 

Issue identified in step 4 of the deployment, but this is an issue throughout.

**Comment by dcint** [comment]
We will address with new tearraform module layout.
