### ISSUE TITLE
Update firewall

### ISSUE THREAD

**Issue by ibersanoMS** [Azure/aks-baseline-windows#32]
- Only a single IP address for AFW is deployed, please follow the AKS baseline for the sake of alignment. (align with AKS baseline)
- Tunnelfront rules – a bit surprised to see those still in there, but if you are going to keep them in there, please at least limit them to AzureCloud.<region> instead of *. (align with AKS baseline)

**Comment by dcint** [comment]
Created zones for pip and fw config. Working on fw rules

**Comment by dcint** [comment]
@ckittel why are they deploying 3 public ip addresses for firewall in aks baseline? Is this to prevent port exhaustion. The drawing says it's an outbound firewall. Just trying to understand why 3 public ip addresses for firewall.

**Comment by ckittel** [comment]
Yup, that's why. Our product docs call this out as well when combining AKS and Azure Firewall for egress. Three was a semi-abritraty number. Not one, and not a lot.

**Comment by dcint** [comment]
Added 3 public ip addresses.
