### ISSUE TITLE
Update AKS cluster 

### ISSUE THREAD

**Issue by ibersanoMS** [Azure/aks-baseline-windows#39]
- Update version to 1.25
- Use naming convention for system node pool from AKS baseline
- System node pool should have three nodes
- Missing AZ zone deployment on nodepools
- Align nodepool configuration settings with AKS baseline
- Take control of the name of the managed resources resource group
- Set network policy choice explicitly 
- Disable local accounts
- System nodepool nissing CriticalAddonsOnly taint
-

**Comment by dcint** [comment]
I'll align to aks baseline. Came in on tail end of first release.

**Comment by dcint** [comment]
Everything updated except for naming convention.  I think should change naming convention when we migrate terraform code to new module structure.
