### ISSUE TITLE
Validate windows disk size choice

### ISSUE THREAD

**Issue by ibersanoMS** [Azure/aks-baseline-windows#41]
Chad -> I was surprised to see such a small disk on the windows node pool and also no explicitly ephemeral os disk choice listed.  Please validate that your disk size choice is guidance and be explicit about the use of ephemeral disk usage. 

Identified in step 7

**Comment by dcint** [comment]
I removed the defined disk size, changed VM size (Standard_DS4_v2) to accommodate cache size for ephemeral disk. Default size for OS disk is 128 if not defined.
