### ISSUE TITLE
Check Terraform support for AKV secrets

### ISSUE THREAD

**Issue by ibersanoMS** [Azure/aks-baseline-windows#43]
Chad ->AKV secrets provider is supported in TF as of about a year ago.  Can you please re-check this.  (looks like it was available as of 2.89)

**Comment by dcint** [comment]
Yes, it is available and the terraform has been updated to use it.

**Comment by ckittel** [comment]
@dcint -- can you please update the instructions then, as it says it is not available, and is asking the user to do it by hand.  See step 7.

**Comment by dcint** [comment]
We should remove all step md files with win in name. There is no need for same instructions. Updates have been done to non-win md's. I'll send a note out to team asking if I can delete them.
