### ISSUE TITLE
Add Windows jumpbox to architecture

### ISSUE THREAD

**Issue by ibersanoMS** [Azure/aks-baseline-windows#45]
Users should be instructed to use a Windows VM to deploy their workloads and access the AKS cluster, not the domain controller. The architecture has a Linux VM currently which needs to be replaced with a Windows VM

**Comment by dcint** [comment]
Added windows jump box to lz-Spoke vnet in DC subnet.
*Note: ran into issue with extension to install az cli Inconsistent deployment. When installing via extension az aks install-cli would not install. Seems like az cli install does not complete correctly.
